/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion.gui;

import Gestion.dto.Carrera;
import Gestion.dto.Corredor;
import Gestion.dto.Gestor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PABLO
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    private Gestor gestor= null;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        gestor= new Gestor();
        initComponents();
        inicializarTablaCarreras();
        mostrarCarreras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloCarrera = new javax.swing.JLabel();
        jScrollPaneCarrera = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        TituloCorredor = new javax.swing.JLabel();
        jScrollPaneCorredor = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jButtonBaja = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuAlta = new javax.swing.JMenu();
        jMenuItemCarrera = new javax.swing.JMenuItem();
        jMenuItemCorredor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloCarrera.setText("CARRERAS");

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Lugar", "Fecha", "Participantes"
            }
        ));
        jTableCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCarrerasMouseClicked(evt);
            }
        });
        jScrollPaneCarrera.setViewportView(jTableCarreras);

        TituloCorredor.setText("CORREDORES");

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Fecha Nac", "Telefono", "DNI"
            }
        ));
        jScrollPaneCorredor.setViewportView(jTableCorredores);

        jButtonBaja.setText("Dar de Baja");

        jMenuAlta.setText("Alta...");

        jMenuItemCarrera.setText("Carrera");
        jMenuItemCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarreraActionPerformed(evt);
            }
        });
        jMenuAlta.add(jMenuItemCarrera);

        jMenuItemCorredor.setText("Corredor");
        jMenuAlta.add(jMenuItemCorredor);

        jMenuBar.add(jMenuAlta);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPaneCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBaja))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(TituloCorredor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(TituloCarrera)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TituloCarrera)
                .addGap(22, 22, 22)
                .addComponent(jScrollPaneCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TituloCorredor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPaneCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBaja)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarreraActionPerformed
        JDialogCarrera carrera= new JDialogCarrera(this, true, gestor);
        carrera.setVisible(true);
        mostrarCarreras();
    }//GEN-LAST:event_jMenuItemCarreraActionPerformed

    
    private void jTableCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCarrerasMouseClicked
        // TODO add your handling code here:
        int fila= jTableCarreras.getSelectedRow();
        if (fila!=-1) {
            String nombreCarrera = String.valueOf(jTableCarreras.getValueAt(fila, 0));
            mostrarCorredores(nombreCarrera);
            System.out.println("Carrera"+nombreCarrera);
        }
    }//GEN-LAST:event_jTableCarrerasMouseClicked
    
     private void inicializarTablaCarreras()
    {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre","Lugar","Fecha","Participantes"});
        jTableCarreras.setModel(dtm);
    }
    
     private void mostrarCarreras(){
         ArrayList<Carrera> listaCarreras= gestor.getListaCarrera();
         DefaultTableModel dtm = (DefaultTableModel)jTableCarreras.getModel();
         for (int i = 0; i < listaCarreras.size(); i++) {
           dtm.addRow(listaCarreras.get(i).toArrayString());  
         }
         
     }
     private void inicializarTablaCorredor(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre","Direccion","Fecha Nac","Telefono","DNI"});
        jTableCorredores.setModel(dtm);
    }
     
        
    private void mostrarCorredores(String nombreCarrera){
        Carrera carrera = gestor.BuscarCarrera(nombreCarrera);
        ArrayList<Corredor> listaCorredores= carrera.getListaCorredores();
        DefaultTableModel dtm = (DefaultTableModel)jTableCorredores.getModel();
        for (int i = 0; i < listaCorredores.size(); i++) {
           dtm.addRow(listaCorredores.get(i).toArrayString());
        } 
    }

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloCarrera;
    private javax.swing.JLabel TituloCorredor;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JMenu jMenuAlta;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCarrera;
    private javax.swing.JMenuItem jMenuItemCorredor;
    private javax.swing.JScrollPane jScrollPaneCarrera;
    private javax.swing.JScrollPane jScrollPaneCorredor;
    private javax.swing.JTable jTableCarreras;
    private javax.swing.JTable jTableCorredores;
    // End of variables declaration//GEN-END:variables
}
