/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion.gui;

import Gestion.dto.Carrera;
import Gestion.dto.ComponenteTemporizador;
import Gestion.dto.Corredor;
import Gestion.dto.Gestor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PABLO
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    private Gestor gestor= null;
    private ComponenteTemporizador temporizador;
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        gestor= new Gestor();
        initComponents();
        inicializarTablaCarreras();
        inicializarTablaCorredorTotales();
        inicializarTablaCorredor();
        mostrarCarreras();
        mostrarCorredoresTotales();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloCarrera = new javax.swing.JLabel();
        jScrollPaneCarrera = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        TituloCorredor = new javax.swing.JLabel();
        jScrollPaneCorredor = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jButtonBajaCarrera = new javax.swing.JButton();
        TituloCorredor1 = new javax.swing.JLabel();
        jScrollPaneCorredorTot = new javax.swing.JScrollPane();
        jTableCorredoresTot = new javax.swing.JTable();
        jButtonAñadir = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButtonBajaCorredor = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuAlta = new javax.swing.JMenu();
        jMenuItemCarrera = new javax.swing.JMenuItem();
        jMenuItemCorredor = new javax.swing.JMenuItem();
        jMenumodificar = new javax.swing.JMenu();
        jMenuItemCarreraModificar = new javax.swing.JMenuItem();
        jMenuItemCorredorModificar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloCarrera.setText("CARRERAS");

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Lugar", "Fecha", "Participantes"
            }
        ));
        jTableCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCarrerasMouseClicked(evt);
            }
        });
        jScrollPaneCarrera.setViewportView(jTableCarreras);

        TituloCorredor.setText("CORREDORES");

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Fecha Nac", "Telefono", "DNI"
            }
        ));
        jScrollPaneCorredor.setViewportView(jTableCorredores);

        jButtonBajaCarrera.setText("Dar de Baja");
        jButtonBajaCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaCarreraActionPerformed(evt);
            }
        });

        TituloCorredor1.setText("CORREDORES TOTALES");

        jTableCorredoresTot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Fecha Nac", "Telefono", "DNI"
            }
        ));
        jScrollPaneCorredorTot.setViewportView(jTableCorredoresTot);

        jButtonAñadir.setText("Añadir Corredor a Carrera");
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jButtonBajaCorredor.setText("Dar de Baja");
        jButtonBajaCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaCorredorActionPerformed(evt);
            }
        });

        jMenuAlta.setText("Alta...");

        jMenuItemCarrera.setText("Carrera");
        jMenuItemCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarreraActionPerformed(evt);
            }
        });
        jMenuAlta.add(jMenuItemCarrera);

        jMenuItemCorredor.setText("Corredor");
        jMenuItemCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCorredorActionPerformed(evt);
            }
        });
        jMenuAlta.add(jMenuItemCorredor);

        jMenuBar.add(jMenuAlta);

        jMenumodificar.setText("Modificar");

        jMenuItemCarreraModificar.setText("Carrera");
        jMenuItemCarreraModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarreraModificarActionPerformed(evt);
            }
        });
        jMenumodificar.add(jMenuItemCarreraModificar);

        jMenuItemCorredorModificar.setText("Corredor");
        jMenuItemCorredorModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCorredorModificarActionPerformed(evt);
            }
        });
        jMenumodificar.add(jMenuItemCorredorModificar);

        jMenuBar.add(jMenumodificar);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TituloCarrera)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(312, 312, 312)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonBajaCarrera))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TituloCorredor))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPaneCorredorTot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TituloCorredor1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBajaCorredor)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAñadir)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloCarrera)
                    .addComponent(jButtonBajaCarrera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneCarrera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(TituloCorredor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBajaCorredor)
                    .addComponent(TituloCorredor1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneCorredorTot, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAñadir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarreraActionPerformed
        JDialogCarrera carrera= new JDialogCarrera(this, true, gestor);
        carrera.setVisible(true);
        mostrarCarreras();
    }//GEN-LAST:event_jMenuItemCarreraActionPerformed

    
    private void jTableCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCarrerasMouseClicked
        // TODO add your handling code here:
        int fila= jTableCarreras.getSelectedRow();
        if (fila!=-1) {
            String nombreCarrera = String.valueOf(jTableCarreras.getValueAt(fila, 0));
            mostrarCorredores(nombreCarrera);
            
        }
    }//GEN-LAST:event_jTableCarrerasMouseClicked

    private void jButtonBajaCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaCarreraActionPerformed
        int fila= jTableCarreras.getSelectedRow();
        if (fila!=-1) {
            String nombreCarrera = String.valueOf(jTableCarreras.getValueAt(fila, 0));
            gestor.DarBajaCarrera(nombreCarrera);
            mostrarCarreras();
        }
    }//GEN-LAST:event_jButtonBajaCarreraActionPerformed

    private void jMenuItemCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCorredorActionPerformed
        DialogoCorredor corredor= new DialogoCorredor(this, true, gestor);
        corredor.setVisible(true);
        mostrarCorredoresTotales();
    }//GEN-LAST:event_jMenuItemCorredorActionPerformed

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        // TODO add your handling code here:
        boolean correcto=false;
        String nombreCarrera="";
        int filacarrera= jTableCarreras.getSelectedRow();
        if (filacarrera!=-1) {
             nombreCarrera = String.valueOf(jTableCarreras.getValueAt(filacarrera, 0));
            correcto=true;
        }
         
        int filacorredor= jTableCorredoresTot.getSelectedRow();
        if (filacorredor!=-1) {
            String dni = String.valueOf(jTableCorredoresTot.getValueAt(filacorredor, 4));
            if(correcto)
            {
                gestor.AñadirCorredorCarrera(nombreCarrera, dni);
            }
        }
        System.out.println("");
        mostrarCorredores(nombreCarrera);
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jButtonBajaCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaCorredorActionPerformed
        // TODO add your handling code here:
        int fila= jTableCorredoresTot.getSelectedRow();
        if (fila!=-1) {
            String dni = String.valueOf(jTableCorredoresTot.getValueAt(fila, 4));
            gestor.DarBajaCorredor(dni);
            gestor.BorrarCorredorCarrera(dni);
            mostrarCorredoresTotales();
        }
    }//GEN-LAST:event_jButtonBajaCorredorActionPerformed

    private void jMenuItemCarreraModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarreraModificarActionPerformed
        // TODO add your handling code here:
         int fila= jTableCorredoresTot.getSelectedRow();
        if(fila!=-1){
            String nombreCarrera= String.valueOf(jTableCarreras.getValueAt(fila, 0));
            gestor.setNombreCarreraModificar(nombreCarrera);
            JDialogCarrera carrera= new JDialogCarrera(this, true, gestor);
            carrera.setVisible(true);
            mostrarCarreras();
            gestor.setNombreCarreraModificar("");      
        }
        
    }//GEN-LAST:event_jMenuItemCarreraModificarActionPerformed

    private void jMenuItemCorredorModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCorredorModificarActionPerformed
        // TODO add your handling code here:
        int fila = jTableCorredoresTot.getSelectedRow();
        if(fila!=-1){
            String dni= String.valueOf(jTableCorredoresTot.getValueAt(fila, 4));
            gestor.setDniModificar(dni);
            DialogoCorredor corredor= new DialogoCorredor(this, true, gestor);
            corredor.setVisible(true);
            mostrarCorredoresTotales();   
            gestor.setDniModificar("");
        }
        
    }//GEN-LAST:event_jMenuItemCorredorModificarActionPerformed
    
     private void inicializarTablaCarreras()
    {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre","Lugar","Fecha","Participantes"});
        jTableCarreras.setModel(dtm);
    }
    
     private void mostrarCarreras(){
         inicializarTablaCarreras();
         ArrayList<Carrera> listaCarreras= gestor.getListaCarrera();
         DefaultTableModel dtm = (DefaultTableModel)jTableCarreras.getModel();
         for (int i = 0; i < listaCarreras.size(); i++) {
           dtm.addRow(listaCarreras.get(i).toArrayString());  
         }
         
     }
     
     private void inicializarTablaCorredorTotales(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre","Direccion","Fecha Nac","Telefono","DNI"});
        jTableCorredoresTot.setModel(dtm);
    }
     
    private void mostrarCorredoresTotales(){
        inicializarTablaCorredorTotales();
        ArrayList<Corredor> listaCorredores=gestor.getListaCorredor();
        DefaultTableModel dtm = (DefaultTableModel)jTableCorredoresTot.getModel();
        for (int i = 0; i < listaCorredores.size(); i++) {
           dtm.addRow(listaCorredores.get(i).toArrayStringTotales());
        } 
    }
    
    private void inicializarTablaCorredor(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Dorsal","Nombre","Direccion","Fecha Nac","Telefono","DNI"});
        jTableCorredores.setModel(dtm);
    }
         
    private void mostrarCorredores(String nombreCarrera){
        inicializarTablaCorredor();
        Carrera carrera = gestor.BuscarCarrera(nombreCarrera);
        ArrayList<Corredor> listaCorredores= carrera.getListaCorredores();
        DefaultTableModel dtm = (DefaultTableModel)jTableCorredores.getModel();
        System.out.println("listaCorredores.size "+listaCorredores.size());
        
        for (int i = 0; i < listaCorredores.size(); i++) {
            dtm.addRow(listaCorredores.get(i).toArrayStringDorsal());
           
        } 
    }

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloCarrera;
    private javax.swing.JLabel TituloCorredor;
    private javax.swing.JLabel TituloCorredor1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonBajaCarrera;
    private javax.swing.JButton jButtonBajaCorredor;
    private javax.swing.JMenu jMenuAlta;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCarrera;
    private javax.swing.JMenuItem jMenuItemCarreraModificar;
    private javax.swing.JMenuItem jMenuItemCorredor;
    private javax.swing.JMenuItem jMenuItemCorredorModificar;
    private javax.swing.JMenu jMenumodificar;
    private javax.swing.JScrollPane jScrollPaneCarrera;
    private javax.swing.JScrollPane jScrollPaneCorredor;
    private javax.swing.JScrollPane jScrollPaneCorredorTot;
    private javax.swing.JTable jTableCarreras;
    private javax.swing.JTable jTableCorredores;
    private javax.swing.JTable jTableCorredoresTot;
    // End of variables declaration//GEN-END:variables
}
